### ISSUE TITLE
R1: Confusion over index of arguments

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#144]
#143

> The explicit representation of the index of the arguments (1, 2, 3, ...) in the proposed visualization doesn't seem to add much value. I don't understand why the authors didn't act on the hint of one of their users in the test study who was also confused by these numbers. These number should have been omitted.

**Comment by jalanmiddleton** [comment]
Can't change the design right now, but I can modify the paragraph on page 3 in section III.B to be more clear about what the numbers are.

**Comment by CaptainEmerson** [comment]
When you talk about the design, you could also say that we anticipated that the feature would be useful, but the user study in Section X demonstrated that the feature was more confusing than useful (or whatever the result was)
