### ISSUE TITLE
R1: Unscalable 

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#145]
#143

> In addition, drawing all 27 arguments as in Fig. 10 illustrates that this approach is not scalable (although it illustrated the pathology in the source).

**Comment by jalanmiddleton** [comment]
Nothing here for now.

**Comment by CaptainEmerson** [comment]
I'd say something to the effect of "although the visualization in this case is not scaling well with this 27-argument function, it nonetheless serves a useful purpose -- this awkward-looking visualization is indicative of at least one awkwardly design spreadsheet."

**Comment by CaptainEmerson** [comment]
This basically is what the reviewer is saying, which bears repeating. Also, thank the anonymous reviewers in the acks.
