### ISSUE TITLE
R1: Clarification of type of visualization

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#146]
#143

> If all this visualization offers to the user is to explore a call tree, wouldn't a simple, textual version of a tree with indentation suffice?

---

> It seems to me all the research that has been done on call trees for single program executions (over probably 20 years) can be applied to this area of spreadsheet logic. This applies not only to the analysis but also to visualizing these call structures.

**Comment by jalanmiddleton** [comment]
I could extend the first paragraph in section III.E to address the questions in talking why we chose the tree. Don't want to spend too much time on it, though.

**Comment by CaptainEmerson** [comment]
I'd say it's worth a paragraph.

**Comment by jalanmiddleton** [comment]
fixed in e5af52856b86165ee831667735eb0b4a3f5c0338
