### ISSUE TITLE
R2: Unanswered questions for scenarios

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#148]
#143
- How could users judge if something is a bad smell if they are not expert in spreadsheets? 
- Where to look in the huge tree for bad smells? 
- Wouldn’t novice user of spreadsheets be overwhelmed if they see all possible uses of a formula (instead of a few selected good ones)? 
- How to discern “good” uses from “bad” uses?

**Comment by jalanmiddleton** [comment]
These were the limitations I addressed myself, too. Not sure what to do other than polish up the sections where I discussed them.

**Comment by CaptainEmerson** [comment]
Apparently this reviewer missed them. Yes, take a look at each place you mentioned each one, and make sure the point is clear. If it makes sense, you could turn these disparate pieces (maybe "open questions" or "future work") and turn them into their own section -- it'd make it less likely that the reader wouldn't see them.
