### ISSUE TITLE
R2: Figures have poor resolution

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#152]
#143

> Some figures have poor resolution

**Comment by jalanmiddleton** [comment]
Really need to figure out how to get PDFs/SVGs on there. When I tried before, the lines would always be distorted, or the transparency ruined, etc.

**Comment by CaptainEmerson** [comment]
I said I'd do this, but since we've got more time, you can do it. You'll need to ask for acrobat.
