### ISSUE TITLE
R3: Reduce discussion of limitations

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#158]
#143

> The authors spend more than a page discussing limitations of the user study as well as of the overall approach. While discussing limitations is an important part of empirical research papers, I would have preferred to see more examples of insights about the Enron dataset gained with the tool.

**Comment by jalanmiddleton** [comment]
Don't call section 6 "limitations." Reduce each individual section to a paragraph?

**Comment by CaptainEmerson** [comment]
Correct me if I'm wrong: The reviewer is under the impression that this is a "study limitations" section, when it's really a "visualization limitations" section.

Clarify. Yes, a section heading will help, but clearer writing will help too, especially at the front of the section and each paragraph. Like: "The study revealed several limitations of the viz. One limitation of hte viz was... Another limitation of the viz was..."
