### ISSUE TITLE
ref?

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#34]
![snippet](https://lh3.googleusercontent.com/-o_dFVIXs6dk/VxgrjZD1afI/AAAAAAAAD-I/WYoa3nzo9UA/s800/%25255BUNSET%25255D.png)

ref?

**Comment by jalanmiddleton** [comment]
The ref is the footnote, really. It didn't come directly from a paper, but I have seen plenty of other papers do the same kind of footnoting with this site specifically...

**Comment by CaptainEmerson** [comment]
Ok, but the footnote isn't near the name.

**Comment by jalanmiddleton** [comment]
Do I need one for the homepage of the site and another for the horror stories page?

**Comment by CaptainEmerson** [comment]
Just horror stories is fine.
