### ISSUE TITLE
complicated word where simple word will do. con...

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#36]
![snippet](https://lh3.googleusercontent.com/-mmsmX94L6iY/VxgrkETcaqI/AAAAAAAAD-Q/S96SdyRwa0Q/s800/%25255BUNSET%25255D.png)

complicated word where simple word will do. consider that many people will not speak English as a first language. Your primary goal is to communicate with your audience.

**Comment by jalanmiddleton** [comment]
Precisely: characteristic prolixity customarily obfuscates linguistic content; redundant, unnecessary pleonasm threatens communicative incapacitation. Infelicitous, indubitably...

**Comment by CaptainEmerson** [comment]
As a general practice, please close your issues with commits. E.g., make one commit with just this word replacement, with a comment like "Fixes #36". The issue gets closed automatically.

**Comment by JustinAMiddleton** [comment]
Oh, yeah, gotcha.
