### ISSUE TITLE
give the tool a name, put it in a macro (so you...

### ISSUE THREAD

**Issue by jalanmiddleton** [DeveloperLiberationFront/Excel-Function-Visualizer#66]
![snippet](https://lh3.googleusercontent.com/-NJTD1OtrAUo/VxgrrUX-1OI/AAAAAAAAEAI/gHfrRHcGmjU/s800/%25255BUNSET%25255D.png)

give the tool a name, put it in a macro (so you can change it later), and apply it in your document.

**Comment by CaptainEmerson** [comment]
PERQUIMANS‽

**Comment by jalanmiddleton** [comment]
Was having some trouble with the interrobang itself -- but `?!` works just as well for now.
